# Before building this image oracle/database:18.4.0-xe must be available at your private registry
# See https://github.com/marcelo-ochoa/docker-images/blob/master/OracleDatabase/README.md for more details
# Finally build using ./buildDockerImage.sh script
FROM alpine/git:latest AS PCSource
LABEL maintainer="Marcelo Ochoa <mochoa@scotas.com>"
ARG REPO_URL
ENV REPO_URL ${REPO_URL:-https://github.com/scotas/pc.git}
ARG BRANCH
ENV BRANCH ${BRANCH:-master}

WORKDIR /src

# Clone GitHub Repo from an specific branch
RUN git clone -b $BRANCH $REPO_URL

FROM	oracle/database:18.4.0-xe
LABEL maintainer="Marcelo Ochoa <mochoa@scotas.com>"

USER	root
RUN	yum -y --enablerepo ol7_optional_latest install ant ant-contrib ant-junit apache-ivy && \
	yum clean all

ADD https://www.scotas.com/download/ols/18cR1/ODCI.jar /home/oracle/
ADD https://www.scotas.com/download/ols/18cR1/converter.jar /home/oracle/
ADD https://www.scotas.com/download/ols/18cR1/initsoxx.sql /home/oracle/
ADD https://www.scotas.com/download/ols/18cR1/translator.jar /home/oracle/
ADD https://www.scotas.com/download/ols/18cR1/sqljutl.sql /home/oracle/

# Source of Scotas PC
COPY --from=PCSource --chown=oracle:oinstall /src/pc/ /home/pc/

RUN	mv $ORACLE_HOME/rdbms/jlib/ODCI.jar $ORACLE_HOME/rdbms/jlib/ODCI.jar.bak && \
	mv /home/oracle/ODCI.jar $ORACLE_HOME/rdbms/jlib/ODCI.jar && \
	mv /home/oracle/converter.jar $ORACLE_HOME/rdbms/jlib/converter.jar && \
	mv $ORACLE_HOME/rdbms/admin/initsoxx.sql $ORACLE_HOME/rdbms/admin/initsoxx.sql.bak && \
	mv /home/oracle/initsoxx.sql $ORACLE_HOME/rdbms/admin/initsoxx.sql && \
	chmod a+r $ORACLE_HOME/rdbms/jlib/ODCI.jar && \
	chown oracle:oinstall $ORACLE_HOME/rdbms/jlib/ODCI.jar && \
	chmod a+r $ORACLE_HOME/rdbms/jlib/converter.jar && \
	chown oracle:oinstall $ORACLE_HOME/rdbms/jlib/converter.jar && \
	chmod a+r $ORACLE_HOME/rdbms/admin/initsoxx.sql && \
	chown oracle:oinstall $ORACLE_HOME/rdbms/admin/initsoxx.sql && \
	mkdir -p $ORACLE_HOME/oc4j/sqlj/lib && \
	ln -s $ORACLE_HOME/jdbc/lib/ojdbc8.jar $ORACLE_HOME/jdbc/lib/ojdbc6.jar && \
	mv  /home/oracle/translator.jar /home/oracle/sqljutl.sql $ORACLE_HOME/oc4j/sqlj/lib && \
	chmod a+r $ORACLE_HOME/oc4j/sqlj/lib/translator.jar && \
	chmod a+r $ORACLE_HOME/oc4j/sqlj/lib/sqljutl.sql && \
	chown -R oracle:oinstall $ORACLE_HOME/oc4j && \
	chown -R oracle:oinstall /home/oracle && \
        echo "XEPDB1= \
(DESCRIPTION = \
  (ADDRESS = (PROTOCOL = TCP)(HOST = db)(PORT = 1521)) \
  (CONNECT_DATA = \
    (SERVER = DEDICATED) \
    (SERVICE_NAME = XEPDB1) \
  ) \
)" >> $ORACLE_HOME/network/admin/tnsnames.ora


ENV	JAVA_HOME=$ORACLE_HOME/jdk LD_LIBRARY_PATH=$ORACLE_HOME/lib

WORKDIR	/home
USER	oracle

# Define default command to start Oracle Database. 
CMD	exec /bin/bash
