version: '3.6'
services:
  db:
    image: oracle/database:18.4.0-xe
    hostname: ols
    volumes:
      - db_data:/opt/oracle/oradata # persistent oracle database data. UID/GID 54321:54321
      - /run/shm:/dev/shm
    ports:
      - 1521:1521
      - 9099:9099
    environment:
      - ORACLE_PWD=Oracle_2020      # Remove after first run
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    healthcheck:
      test: exit 0                  # Remove after first run
      interval: 60s
      timeout: 3s
    configs:
      - source: 00-unzip-ols.sh
        target: /opt/oracle/scripts/setup/00-unzip-ols.sh
      - source: 01-ols-ins.sh
        target: /opt/oracle/scripts/setup/01-ols-ins.sh
      - source: 02-clean-up-ols-files.sh
        target: /opt/oracle/scripts/setup/02-clean-up-ols-files.sh
  dev:
    image: ols-dev-xe:2.0.5
    command: ping 127.0.0.1
    hostname: dev
#    volumes:
#      - /home/oracle/github/ols:/home/ols                # OLS source, uncomment if you want to work with live source code
    environment:
      - ORACLE_PWD=Oracle_2020
    deploy:
      mode: replicated
      replicas: 0
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
    healthcheck:
      test: exit 0
      interval: 60s
      timeout: 3s
configs:
  00-unzip-ols.sh:
      file: ../ols-scripts-xe/00-unzip-ols.sh
  01-ols-ins.sh:
      file: ../ols-scripts-xe/01-ols-ins.sh
  02-clean-up-ols-files.sh:
      file: ../ols-scripts-xe/02-clean-up-files.sh
volumes:
  db_data:
    driver_opts:
      type: none
      device: /home/data/db/xe-18c
      o: bind
